---
# Install dependencies on the host
- name: Install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python-pip

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest
# pip install openstacksdk
- name: Install git
  become: yes
  apt:
    name: ['git']
    update_cache: yes
    state: latest

- name: Install dependencies
  tags: always
  become: yes
  apt: 
    name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python-pip']
    state: latest
    install_recommends: no
    update_cache: yes
- name: Install dos2unix
  tags: always
  become: yes
  apt:
    name: dos2unix
    state: latest
    update_cache: yes
