 - name: mkdir the mount point
   become: yes
   shell: |
      mkfs.ext4 /dev/vdb
      sudo mount /dev/vdb /opt
      sleep 3

 - name: auto mount volume
   become: yes
   lineinfile:
      dest: /etc/fstab
      line: "/dev/vdb    /opt    ext4    defaults    0    1"
      state: present
# mkdir the workspace
 - name: mkdir the /opt/workspace
   become: yes
   file:
      path: "{{ item }}"
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: 0755
   with_items:
    - /opt/workspace