- name: Gather facts
  setup:
    gather_subset: all
- name: Add server Configuration in instance
  become: yes
  lineinfile:
    path: /etc/environment
    line: "http_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nhttps_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nftp_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nno_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
    state: present
- name: Install pip3
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  
- name: Install git
  become: yes
  apt:
    name: ['git']
    update_cache: yes
    state: latest

- name: Install dependencies
  tags: always
  become: yes
  apt: 
    name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-pip']
    state: latest
    install_recommends: no
    update_cache: yes

#- name: Update pip3
#  tags: always
#  become: yes
#  pip:
#    name: ['python3-pip']
 #   state: latest

- name: Install dos2unix
  tags: always
  become: yes
  apt:
    name: dos2unix
    state: latest
    update_cache: yes