# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: Couch_db_1
    vol_size: 20
  - vol_name: Couch_db_2
    vol_size: 20
  - vol_name: Couch_db_3
    vol_size: 20
  - vol_name: web_server
    vol_size: 10

# Security group
security_groups:
  - name: test_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: test_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: test_couchdb
    description: "Test security group for couchdb TCP"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: test_backend
    description: "Test security group for backend"
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0
  - name: test_website
    description: "Test security group for website"
    protocol: tcp
    port_range_min: 3000
    port_range_max: 3000
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: test-1
    volumes: ['Couch_db_1']
  - name: test-2
    volumes: ['Couch_db_2']
  - name: test-3
    volumes: ['Couch_db_3']
  - name: webapp
    volumes: ['web_server']
    
instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166 
instance_key_name: test1
instance_flavor: uom.mse.1c4g
