#Team 53
#Melbourne
#@author: Sania Khan(1045290), Kanav Sood(1057606), Gaurang Sharma(1041953), Udit Goel(1042890), Jack Crellin(1168062)
# Create an instance on NeCTAR
- name: Create an instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ item.volumes }}'
    network: qh2-uom-internal
    auto_floating_ip: yes
    wait: yes
    timeout: 800
    state: present
  loop: '{{ instances }}'
  register: os_instance
  
- name: Add server Configuration in instance
  become: yes
  lineinfile:
    path: /etc/environment
    line: "http_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nhttps_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nftp_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nno_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
    state: present
    
- debug:
    msg: "Instance {{ item.openstack.name }} has been created. IP address is {{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

- name: Wait for connection
  wait_for:
    host: "{{ item.openstack.public_v4 }}"
    port: 22
    timeout: 420
    search_regex: OpenSSH
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined
# Add hosts to Ansible in-memory inventory
- name: Add host
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: COMP90024
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined