#Team 53
#Melbourne
#@author: Sania Khan(1045290), Kanav Sood(1057606), Gaurang Sharma(1041953), Udit Goel(1042890), Jack Crellin(1168062)
- name: mkdir the /home/ubuntu/couchdb/slave/data
  become: yes
  file:
    path: /home/ubuntu/couchdb/slave/data
    state: directory
    owner: ubuntu
    group: ubuntu
    
- name: Restart docker service
  raw: sudo systemctl daemon-reload; sudo systemctl restart docker
  
- name: Configure compose
  become: yes
  template:
    src: docker-compose.yaml.j2
    dest: /home/ubuntu/couchdb/slave/docker-compose.yaml

- name: run Couchdb_slave2
  raw: cd /home/ubuntu/couchdb/slave/; sudo systemctl daemon-reload; sudo docker-compose up -d 